export interface ColumnDef {
  name: string;
  type: string;
  nullable?: boolean;
  defaultSql?: string;
}

export interface TableSchema {
  createSql: string;
  columns: ColumnDef[];
  indexes?: string[];
}

export const TABLE_SCHEMAS: Record<string, TableSchema> = {
  Users: {
    createSql: `CREATE TABLE IF NOT EXISTS Users (
      id TEXT PRIMARY KEY,
      full_name TEXT,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      salt TEXT NOT NULL,
      role TEXT CHECK(role IN ('admin', 'teacher', 'student')) NOT NULL DEFAULT 'student',
      phone TEXT,
      district TEXT,
      state TEXT,
      country TEXT DEFAULT 'IN',
      birth_date TEXT,
      father_name TEXT,
      mother_name TEXT,
      grand_father_name TEXT,
      pincode TEXT,
      gender TEXT,
      bio TEXT,
      birth_place TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'full_name', type: 'TEXT' },
      { name: 'email', type: 'TEXT', nullable: false },
      { name: 'password_hash', type: 'TEXT', nullable: false },
      { name: 'salt', type: 'TEXT', nullable: false },
      { name: 'role', type: 'TEXT', nullable: false, defaultSql: "'student'" },
      { name: 'phone', type: 'TEXT' },
      { name: 'district', type: 'TEXT' },
      { name: 'state', type: 'TEXT' },
      { name: 'country', type: 'TEXT', defaultSql: "'IN'" },
      { name: 'birth_date', type: 'TEXT' },
      { name: 'father_name', type: 'TEXT' },
      { name: 'mother_name', type: 'TEXT' },
      { name: 'grand_father_name', type: 'TEXT' },
      { name: 'pincode', type: 'TEXT' },
      { name: 'gender', type: 'TEXT' },
      { name: 'bio', type: 'TEXT' },
      { name: 'birth_place', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_users_email ON Users(email)',
    ],
  },

  OTPs: {
    createSql: `CREATE TABLE IF NOT EXISTS OTPs (
      email TEXT PRIMARY KEY,
      otp TEXT NOT NULL,
      expires_at DATETIME NOT NULL
    )`,
    columns: [
      { name: 'email', type: 'TEXT' },
      { name: 'otp', type: 'TEXT', nullable: false },
      { name: 'expires_at', type: 'DATETIME', nullable: false },
    ],
  },

  Categories: {
    createSql: `CREATE TABLE IF NOT EXISTS Categories (
      id TEXT PRIMARY KEY,
      name TEXT UNIQUE NOT NULL,
      description TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'name', type: 'TEXT', nullable: false },
      { name: 'description', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  Courses: {
    createSql: `CREATE TABLE IF NOT EXISTS Courses (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      title_hi TEXT,
      description TEXT,
      description_hi TEXT,
      category_id TEXT,
      teacher_id TEXT NOT NULL,
      price_inr INTEGER DEFAULT 0,
      price_usd INTEGER DEFAULT 0,
      thumbnail_url TEXT,
      merchant_default_image_url TEXT,
      self_study_enabled INTEGER DEFAULT 0,
      self_study_credit_cost INTEGER DEFAULT 0,
      self_study_only INTEGER DEFAULT 0,
      individual_class_booking_enabled INTEGER DEFAULT 0,
      individual_class_credit_cost INTEGER DEFAULT 0,
      individual_class_duration_minutes INTEGER DEFAULT 30,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (category_id) REFERENCES Categories(id) ON DELETE SET NULL,
      FOREIGN KEY (teacher_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'title', type: 'TEXT', nullable: false },
      { name: 'title_hi', type: 'TEXT' },
      { name: 'description', type: 'TEXT' },
      { name: 'description_hi', type: 'TEXT' },
      { name: 'category_id', type: 'TEXT' },
      { name: 'teacher_id', type: 'TEXT', nullable: false },
      { name: 'price_inr', type: 'INTEGER', defaultSql: '0' },
      { name: 'price_usd', type: 'INTEGER', defaultSql: '0' },
      { name: 'thumbnail_url', type: 'TEXT' },
      { name: 'merchant_default_image_url', type: 'TEXT' },
      { name: 'self_study_enabled', type: 'INTEGER', defaultSql: '0' },
      { name: 'self_study_credit_cost', type: 'INTEGER', defaultSql: '0' },
      { name: 'self_study_only', type: 'INTEGER', defaultSql: '0' },
      { name: 'individual_class_booking_enabled', type: 'INTEGER', defaultSql: '0' },
      { name: 'individual_class_credit_cost', type: 'INTEGER', defaultSql: '0' },
      { name: 'individual_class_duration_minutes', type: 'INTEGER', defaultSql: '30' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_courses_teacher ON Courses(teacher_id)',
      'CREATE INDEX IF NOT EXISTS idx_courses_category ON Courses(category_id)',
    ],
  },

  Batches: {
    createSql: `CREATE TABLE IF NOT EXISTS Batches (
      id TEXT PRIMARY KEY,
      course_id TEXT,
      book_id TEXT,
      name TEXT NOT NULL,
      name_hi TEXT,
      description_en TEXT,
      description_hi TEXT,
      start_date DATETIME,
      end_date DATETIME,
      class_start_time TEXT,
      class_end_time TEXT,
      class_days TEXT,
      self_study_group_enabled INTEGER DEFAULT 1,
      group_class_credit_cost INTEGER DEFAULT 0,
      group_class_credit_unit TEXT DEFAULT 'class',
      credit_deduction_timing TEXT DEFAULT 'on_join',
      status TEXT CHECK(status IN ('upcoming', 'ongoing', 'completed')) DEFAULT 'upcoming',
      seo_json TEXT,
      google_event_id TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (course_id) REFERENCES Courses(id) ON DELETE CASCADE,
      FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE SET NULL
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'course_id', type: 'TEXT' },
      { name: 'book_id', type: 'TEXT' },
      { name: 'name', type: 'TEXT', nullable: false },
      { name: 'name_hi', type: 'TEXT' },
      { name: 'description_en', type: 'TEXT' },
      { name: 'description_hi', type: 'TEXT' },
      { name: 'start_date', type: 'DATETIME' },
      { name: 'end_date', type: 'DATETIME' },
      { name: 'class_start_time', type: 'TEXT' },
      { name: 'class_end_time', type: 'TEXT' },
      { name: 'class_days', type: 'TEXT' },
      { name: 'self_study_group_enabled', type: 'INTEGER', defaultSql: '1' },
      { name: 'group_class_credit_cost', type: 'INTEGER', defaultSql: '0' },
      { name: 'group_class_credit_unit', type: 'TEXT', defaultSql: "'class'" },
      { name: 'credit_deduction_timing', type: 'TEXT', defaultSql: "'on_join'" },
      { name: 'status', type: 'TEXT', defaultSql: "'upcoming'" },
      { name: 'seo_json', type: 'TEXT' },
      { name: 'google_event_id', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_batches_book ON Batches(book_id)',
      'CREATE INDEX IF NOT EXISTS idx_batches_course ON Batches(course_id)',
    ],
  },

  Lessons: {
    createSql: `CREATE TABLE IF NOT EXISTS Lessons (
      id TEXT PRIMARY KEY,
      course_id TEXT,
      book_id TEXT,
      batch_id TEXT,
      chapter_title TEXT DEFAULT 'General',
      title TEXT NOT NULL,
      type TEXT CHECK(type IN ('video', 'audio', 'pdf', 'live', 'image', 'article', 'recording')) NOT NULL,
      content_url TEXT,
      recording_url TEXT,
      order_index INTEGER NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      text_content TEXT,
      text_content_hi TEXT,
      is_free INTEGER DEFAULT 0,
      processing_status TEXT DEFAULT 'pending',
      processing_error TEXT,
      FOREIGN KEY (course_id) REFERENCES Courses(id) ON DELETE CASCADE,
      FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE,
      FOREIGN KEY (batch_id) REFERENCES Batches(id) ON DELETE SET NULL
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'course_id', type: 'TEXT' },
      { name: 'book_id', type: 'TEXT' },
      { name: 'batch_id', type: 'TEXT' },
      { name: 'chapter_title', type: 'TEXT', defaultSql: "'General'" },
      { name: 'title', type: 'TEXT', nullable: false },
      { name: 'type', type: 'TEXT', nullable: false },
      { name: 'content_url', type: 'TEXT' },
      { name: 'recording_url', type: 'TEXT' },
      { name: 'order_index', type: 'INTEGER', nullable: false },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'text_content', type: 'TEXT' },
      { name: 'text_content_hi', type: 'TEXT' },
      { name: 'is_free', type: 'INTEGER', defaultSql: '0' },
      { name: 'processing_status', type: 'TEXT', defaultSql: "'pending'" },
      { name: 'processing_error', type: 'TEXT' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_lessons_processing_status ON Lessons(processing_status)',
      'CREATE INDEX IF NOT EXISTS idx_lessons_course ON Lessons(course_id)',
    ],
  },

  Enrollments: {
    createSql: `CREATE TABLE IF NOT EXISTS Enrollments (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      course_id TEXT,
      book_id TEXT,
      batch_id TEXT,
      progress INTEGER NOT NULL DEFAULT 0,
      certificate_eligible INTEGER DEFAULT 0,
      certificate_issued INTEGER DEFAULT 0,
      certificate_id TEXT,
      certificate_issued_at DATETIME,
      certificate_issued_by TEXT,
      status TEXT CHECK(status IN ('active', 'revoked', 'completed', 'cancelled')) NOT NULL DEFAULT 'active',
      payment_id TEXT,
      payment_status TEXT DEFAULT 'pending',
      amount_paid INTEGER DEFAULT 0,
      payment_source TEXT,
      purchased_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (course_id) REFERENCES Courses(id) ON DELETE CASCADE,
      FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE,
      FOREIGN KEY (batch_id) REFERENCES Batches(id) ON DELETE SET NULL
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'course_id', type: 'TEXT' },
      { name: 'book_id', type: 'TEXT' },
      { name: 'batch_id', type: 'TEXT' },
      { name: 'progress', type: 'INTEGER', nullable: false, defaultSql: '0' },
      { name: 'certificate_eligible', type: 'INTEGER', defaultSql: '0' },
      { name: 'certificate_issued', type: 'INTEGER', defaultSql: '0' },
      { name: 'certificate_id', type: 'TEXT' },
      { name: 'certificate_issued_at', type: 'DATETIME' },
      { name: 'certificate_issued_by', type: 'TEXT' },
      { name: 'status', type: 'TEXT', nullable: false, defaultSql: "'active'" },
      { name: 'payment_id', type: 'TEXT' },
      { name: 'payment_status', type: 'TEXT', defaultSql: "'pending'" },
      { name: 'amount_paid', type: 'INTEGER', defaultSql: '0' },
      { name: 'payment_source', type: 'TEXT' },
      { name: 'purchased_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_enrollments_user ON Enrollments(user_id)',
      'CREATE INDEX IF NOT EXISTS idx_enrollments_course ON Enrollments(course_id)',
      'CREATE INDEX IF NOT EXISTS idx_enrollments_user_course ON Enrollments(user_id, course_id)',
      'CREATE INDEX IF NOT EXISTS idx_enrollments_batch ON Enrollments(batch_id)',
    ],
  },

  LiveSessions: {
    createSql: `CREATE TABLE IF NOT EXISTS LiveSessions (
      id TEXT PRIMARY KEY,
      course_id TEXT,
      book_id TEXT,
      batch_id TEXT,
      teacher_id TEXT NOT NULL,
      title TEXT,
      start_time DATETIME NOT NULL,
      rtc_room_id TEXT NOT NULL UNIQUE,
      status TEXT CHECK(status IN ('scheduled', 'live', 'ended')) DEFAULT 'scheduled',
      recording_id TEXT,
      recording_status TEXT DEFAULT 'pending',
      is_free INTEGER DEFAULT 0,
      google_event_id TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (course_id) REFERENCES Courses(id) ON DELETE CASCADE,
      FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE,
      FOREIGN KEY (batch_id) REFERENCES Batches(id) ON DELETE SET NULL,
      FOREIGN KEY (teacher_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'course_id', type: 'TEXT' },
      { name: 'book_id', type: 'TEXT' },
      { name: 'batch_id', type: 'TEXT' },
      { name: 'teacher_id', type: 'TEXT', nullable: false },
      { name: 'title', type: 'TEXT' },
      { name: 'start_time', type: 'DATETIME', nullable: false },
      { name: 'rtc_room_id', type: 'TEXT', nullable: false },
      { name: 'status', type: 'TEXT', defaultSql: "'scheduled'" },
      { name: 'recording_id', type: 'TEXT' },
      { name: 'recording_status', type: 'TEXT', defaultSql: "'pending'" },
      { name: 'is_free', type: 'INTEGER', defaultSql: '0' },
      { name: 'google_event_id', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_livesessions_teacher ON LiveSessions(teacher_id)',
      'CREATE INDEX IF NOT EXISTS idx_livesessions_course ON LiveSessions(course_id)',
      'CREATE INDEX IF NOT EXISTS idx_livesessions_batch ON LiveSessions(batch_id)',
    ],
  },

  LiveSignaling: {
    createSql: `CREATE TABLE IF NOT EXISTS LiveSignaling (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL,
      user_id TEXT NOT NULL,
      type TEXT NOT NULL,
      data TEXT NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'session_id', type: 'TEXT', nullable: false },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'type', type: 'TEXT', nullable: false },
      { name: 'data', type: 'TEXT', nullable: false },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  Attendance: {
    createSql: `CREATE TABLE IF NOT EXISTS Attendance (
      id TEXT PRIMARY KEY,
      session_id TEXT NOT NULL,
      user_id TEXT NOT NULL,
      joined_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      left_at DATETIME,
      FOREIGN KEY (session_id) REFERENCES LiveSessions(id) ON DELETE CASCADE,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'session_id', type: 'TEXT', nullable: false },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'joined_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'left_at', type: 'DATETIME' },
    ],
  },

  Exams: {
    createSql: `CREATE TABLE IF NOT EXISTS Exams (
      id TEXT PRIMARY KEY,
      course_id TEXT,
      book_id TEXT,
      batch_id TEXT,
      teacher_id TEXT,
      title TEXT NOT NULL,
      description TEXT,
      passing_score INTEGER NOT NULL DEFAULT 50,
      duration_minutes INTEGER DEFAULT 0,
      is_published INTEGER DEFAULT 0,
      total_marks INTEGER DEFAULT 0,
      scheduled_at DATETIME,
      end_at DATETIME,
      google_event_id TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (course_id) REFERENCES Courses(id) ON DELETE CASCADE,
      FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE,
      FOREIGN KEY (batch_id) REFERENCES Batches(id) ON DELETE SET NULL,
      FOREIGN KEY (teacher_id) REFERENCES Users(id) ON DELETE SET NULL
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'course_id', type: 'TEXT' },
      { name: 'book_id', type: 'TEXT' },
      { name: 'batch_id', type: 'TEXT' },
      { name: 'teacher_id', type: 'TEXT' },
      { name: 'title', type: 'TEXT', nullable: false },
      { name: 'description', type: 'TEXT' },
      { name: 'passing_score', type: 'INTEGER', nullable: false, defaultSql: '50' },
      { name: 'duration_minutes', type: 'INTEGER', defaultSql: '0' },
      { name: 'is_published', type: 'INTEGER', defaultSql: '0' },
      { name: 'total_marks', type: 'INTEGER', defaultSql: '0' },
      { name: 'scheduled_at', type: 'DATETIME' },
      { name: 'end_at', type: 'DATETIME' },
      { name: 'google_event_id', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_exams_course ON Exams(course_id)',
      'CREATE INDEX IF NOT EXISTS idx_exams_batch ON Exams(batch_id)',
    ],
  },

  ExamQuestions: {
    createSql: `CREATE TABLE IF NOT EXISTS ExamQuestions (
      id TEXT PRIMARY KEY,
      exam_id TEXT NOT NULL,
      question_text TEXT NOT NULL,
      options_json TEXT NOT NULL,
      correct_option_index INTEGER NOT NULL DEFAULT 0,
      marks INTEGER NOT NULL DEFAULT 1,
      order_index INTEGER NOT NULL DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (exam_id) REFERENCES Exams(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'exam_id', type: 'TEXT', nullable: false },
      { name: 'question_text', type: 'TEXT', nullable: false },
      { name: 'options_json', type: 'TEXT', nullable: false },
      { name: 'correct_option_index', type: 'INTEGER', nullable: false, defaultSql: '0' },
      { name: 'marks', type: 'INTEGER', nullable: false, defaultSql: '1' },
      { name: 'order_index', type: 'INTEGER', nullable: false, defaultSql: '0' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_exam_questions_exam ON ExamQuestions(exam_id)',
    ],
  },

  ExamAttempts: {
    createSql: `CREATE TABLE IF NOT EXISTS ExamAttempts (
      id TEXT PRIMARY KEY,
      exam_id TEXT NOT NULL,
      user_id TEXT NOT NULL,
      answers_json TEXT NOT NULL,
      score INTEGER NOT NULL DEFAULT 0,
      score_percent INTEGER NOT NULL DEFAULT 0,
      total_marks INTEGER NOT NULL DEFAULT 0,
      passed INTEGER DEFAULT 0,
      submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (exam_id) REFERENCES Exams(id) ON DELETE CASCADE,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'exam_id', type: 'TEXT', nullable: false },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'answers_json', type: 'TEXT', nullable: false },
      { name: 'score', type: 'INTEGER', nullable: false, defaultSql: '0' },
      { name: 'score_percent', type: 'INTEGER', nullable: false, defaultSql: '0' },
      { name: 'total_marks', type: 'INTEGER', nullable: false, defaultSql: '0' },
      { name: 'passed', type: 'INTEGER', defaultSql: '0' },
      { name: 'submitted_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_examattempts_user ON ExamAttempts(user_id)',
      'CREATE INDEX IF NOT EXISTS idx_exam_attempts_user_exam ON ExamAttempts(user_id, exam_id)',
    ],
  },

  CompletedLessons: {
    createSql: `CREATE TABLE IF NOT EXISTS CompletedLessons (
      user_id TEXT NOT NULL,
      lesson_id TEXT NOT NULL,
      completed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      time_spent_seconds INTEGER DEFAULT 0,
      PRIMARY KEY (user_id, lesson_id),
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (lesson_id) REFERENCES Lessons(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'lesson_id', type: 'TEXT', nullable: false },
      { name: 'completed_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'time_spent_seconds', type: 'INTEGER', defaultSql: '0' },
    ],
  },

  Certificates: {
    createSql: `CREATE TABLE IF NOT EXISTS Certificates (
      id TEXT PRIMARY KEY,
      enrollment_id TEXT NOT NULL UNIQUE,
      user_id TEXT NOT NULL,
      course_id TEXT,
      book_id TEXT,
      issued_by TEXT NOT NULL,
      issued_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      notes TEXT,
      FOREIGN KEY (enrollment_id) REFERENCES Enrollments(id) ON DELETE CASCADE,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (course_id) REFERENCES Courses(id) ON DELETE CASCADE,
      FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE,
      FOREIGN KEY (issued_by) REFERENCES Users(id) ON DELETE SET NULL
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'enrollment_id', type: 'TEXT', nullable: false },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'course_id', type: 'TEXT' },
      { name: 'book_id', type: 'TEXT' },
      { name: 'issued_by', type: 'TEXT', nullable: false },
      { name: 'issued_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'notes', type: 'TEXT' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_certificates_user ON Certificates(user_id)',
      'CREATE INDEX IF NOT EXISTS idx_certificates_course ON Certificates(course_id)',
    ],
  },

  Notifications: {
    createSql: `CREATE TABLE IF NOT EXISTS Notifications (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      title TEXT NOT NULL,
      message TEXT NOT NULL,
      type TEXT DEFAULT 'info',
      is_read INTEGER DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'title', type: 'TEXT', nullable: false },
      { name: 'message', type: 'TEXT', nullable: false },
      { name: 'type', type: 'TEXT', defaultSql: "'info'" },
      { name: 'is_read', type: 'INTEGER', defaultSql: '0' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_notifications_user ON Notifications(user_id)',
    ],
  },

  PushSubscriptions: {
    createSql: `CREATE TABLE IF NOT EXISTS PushSubscriptions (
      id TEXT PRIMARY KEY,
      user_id TEXT,
      endpoint TEXT,
      subscription_json TEXT,
      fcm_token TEXT,
      device_id TEXT,
      platform TEXT CHECK(platform IN ('web', 'flutter_android', 'flutter_ios', 'flutter_web')) NOT NULL DEFAULT 'web',
      user_agent TEXT,
      last_active_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: true },
      { name: 'endpoint', type: 'TEXT' },
      { name: 'subscription_json', type: 'TEXT' },
      { name: 'fcm_token', type: 'TEXT' },
      { name: 'device_id', type: 'TEXT' },
      { name: 'platform', type: 'TEXT', nullable: false, defaultSql: "'web'" },
      { name: 'user_agent', type: 'TEXT' },
      { name: 'last_active_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_push_subs_user ON PushSubscriptions(user_id)',
      'CREATE INDEX IF NOT EXISTS idx_push_subs_device ON PushSubscriptions(device_id)',
      'CREATE INDEX IF NOT EXISTS idx_push_subs_fcm ON PushSubscriptions(fcm_token)',
      'CREATE UNIQUE INDEX IF NOT EXISTS idx_push_subs_endpoint ON PushSubscriptions(endpoint)',
    ],
  },

  ChatHistory: {
    createSql: `CREATE TABLE IF NOT EXISTS ChatHistory (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      role TEXT CHECK(role IN ('user', 'assistant')) NOT NULL,
      content TEXT NOT NULL,
      session_id TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'role', type: 'TEXT', nullable: false },
      { name: 'content', type: 'TEXT', nullable: false },
      { name: 'session_id', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  FormTemplates: {
    createSql: `CREATE TABLE IF NOT EXISTS FormTemplates (
      id TEXT PRIMARY KEY,
      slug TEXT UNIQUE NOT NULL,
      title TEXT NOT NULL,
      title_hi TEXT,
      description TEXT,
      description_hi TEXT,
      fields_json TEXT NOT NULL,
      seo_json TEXT,
      theme_json TEXT,
      confirmation_email_body TEXT,
      linked_course_id TEXT,
      book_id TEXT,
      linked_batch_id TEXT,
      auto_enroll INTEGER DEFAULT 0,
      eligibility_criteria TEXT,
      teacher_id TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (teacher_id) REFERENCES Users(id) ON DELETE SET NULL
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'slug', type: 'TEXT', nullable: false },
      { name: 'title', type: 'TEXT', nullable: false },
      { name: 'title_hi', type: 'TEXT' },
      { name: 'description', type: 'TEXT' },
      { name: 'description_hi', type: 'TEXT' },
      { name: 'fields_json', type: 'TEXT', nullable: false },
      { name: 'seo_json', type: 'TEXT' },
      { name: 'theme_json', type: 'TEXT' },
      { name: 'confirmation_email_body', type: 'TEXT' },
      { name: 'linked_course_id', type: 'TEXT' },
      { name: 'book_id', type: 'TEXT' },
      { name: 'linked_batch_id', type: 'TEXT' },
      { name: 'auto_enroll', type: 'INTEGER', defaultSql: '0' },
      { name: 'eligibility_criteria', type: 'TEXT' },
      { name: 'teacher_id', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_form_templates_slug ON FormTemplates(slug)',
    ],
  },

  FormSubmissions: {
    createSql: `CREATE TABLE IF NOT EXISTS FormSubmissions (
      id TEXT PRIMARY KEY,
      template_id TEXT NOT NULL,
      user_id TEXT,
      email TEXT,
      data_json TEXT NOT NULL,
      status TEXT DEFAULT 'pending',
      ai_analysis TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (template_id) REFERENCES FormTemplates(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'template_id', type: 'TEXT', nullable: false },
      { name: 'user_id', type: 'TEXT' },
      { name: 'email', type: 'TEXT' },
      { name: 'data_json', type: 'TEXT', nullable: false },
      { name: 'status', type: 'TEXT', defaultSql: "'pending'" },
      { name: 'ai_analysis', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_form_submissions_template ON FormSubmissions(template_id)',
    ],
  },

  ErrorSessions: {
    createSql: `CREATE TABLE IF NOT EXISTS ErrorSessions (
      id TEXT PRIMARY KEY,
      fingerprint TEXT NOT NULL,
      source TEXT NOT NULL,
      status TEXT DEFAULT 'new',
      severity TEXT DEFAULT 'medium',
      title TEXT NOT NULL,
      error_message TEXT NOT NULL,
      stack_trace TEXT,
      full_payload TEXT,
      ai_prompt TEXT,
      url TEXT,
      user_id TEXT,
      device_info TEXT,
      email_from TEXT,
      email_to TEXT,
      email_subject TEXT,
      repeat_count INTEGER DEFAULT 1,
      last_seen_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'fingerprint', type: 'TEXT', nullable: false },
      { name: 'source', type: 'TEXT', nullable: false },
      { name: 'status', type: 'TEXT', defaultSql: "'new'" },
      { name: 'severity', type: 'TEXT', defaultSql: "'medium'" },
      { name: 'title', type: 'TEXT', nullable: false },
      { name: 'error_message', type: 'TEXT', nullable: false },
      { name: 'stack_trace', type: 'TEXT' },
      { name: 'full_payload', type: 'TEXT' },
      { name: 'ai_prompt', type: 'TEXT' },
      { name: 'url', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT' },
      { name: 'device_info', type: 'TEXT' },
      { name: 'email_from', type: 'TEXT' },
      { name: 'email_to', type: 'TEXT' },
      { name: 'email_subject', type: 'TEXT' },
      { name: 'repeat_count', type: 'INTEGER', defaultSql: '1' },
      { name: 'last_seen_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_error_sessions_fingerprint ON ErrorSessions(fingerprint)',
      'CREATE INDEX IF NOT EXISTS idx_error_sessions_status ON ErrorSessions(status)',
      'CREATE INDEX IF NOT EXISTS idx_error_sessions_updated ON ErrorSessions(updated_at)',
    ],
  },

  ErrorSessionEvents: {
    createSql: `CREATE TABLE IF NOT EXISTS ErrorSessionEvents (
      id TEXT PRIMARY KEY,
      error_session_id TEXT NOT NULL,
      type TEXT NOT NULL,
      payload TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (error_session_id) REFERENCES ErrorSessions(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'error_session_id', type: 'TEXT', nullable: false },
      { name: 'type', type: 'TEXT', nullable: false },
      { name: 'payload', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_error_session_events_session ON ErrorSessionEvents(error_session_id)',
    ],
  },

  JulesJobs: {
    createSql: `CREATE TABLE IF NOT EXISTS JulesJobs (
      id TEXT PRIMARY KEY,
      error_session_id TEXT NOT NULL,
      jules_session_id TEXT,
      prompt TEXT NOT NULL,
      status TEXT DEFAULT 'queued',
      response TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (error_session_id) REFERENCES ErrorSessions(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'error_session_id', type: 'TEXT', nullable: false },
      { name: 'jules_session_id', type: 'TEXT' },
      { name: 'prompt', type: 'TEXT', nullable: false },
      { name: 'status', type: 'TEXT', defaultSql: "'queued'" },
      { name: 'response', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_jules_jobs_session ON JulesJobs(error_session_id)',
      'CREATE INDEX IF NOT EXISTS idx_jules_jobs_status ON JulesJobs(status)',
    ],
  },

  EmailDrafts: {
    createSql: `CREATE TABLE IF NOT EXISTS EmailDrafts (
      id TEXT PRIMARY KEY,
      recipient TEXT NOT NULL,
      subject TEXT NOT NULL,
      body TEXT NOT NULL,
      is_html INTEGER DEFAULT 1,
      status TEXT CHECK(status IN ('draft', 'sent', 'cancelled')) DEFAULT 'draft',
      admin_id TEXT NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      sent_at DATETIME,
      FOREIGN KEY (admin_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'recipient', type: 'TEXT', nullable: false },
      { name: 'subject', type: 'TEXT', nullable: false },
      { name: 'body', type: 'TEXT', nullable: false },
      { name: 'is_html', type: 'INTEGER', defaultSql: '1' },
      { name: 'status', type: 'TEXT', defaultSql: "'draft'" },
      { name: 'admin_id', type: 'TEXT', nullable: false },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'sent_at', type: 'DATETIME' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_email_drafts_admin ON EmailDrafts(admin_id)',
      'CREATE INDEX IF NOT EXISTS idx_email_drafts_status ON EmailDrafts(status)',
    ],
  },

  Subscribers: {
    createSql: `CREATE TABLE IF NOT EXISTS Subscribers (
      email TEXT PRIMARY KEY,
      subscribed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      status TEXT DEFAULT 'active'
    )`,
    columns: [
      { name: 'email', type: 'TEXT' },
      { name: 'subscribed_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'status', type: 'TEXT', defaultSql: "'active'" },
    ],
  },

  BroadcastDrafts: {
    createSql: `CREATE TABLE IF NOT EXISTS BroadcastDrafts (
      id TEXT PRIMARY KEY,
      subject TEXT DEFAULT '',
      message TEXT NOT NULL,
      type TEXT CHECK(type IN ('draft', 'history')) DEFAULT 'draft',
      target_type TEXT DEFAULT 'all',
      target_id TEXT DEFAULT '',
      custom_emails TEXT DEFAULT '',
      send_email INTEGER DEFAULT 1,
      send_notification INTEGER DEFAULT 1,
      send_push INTEGER DEFAULT 0,
      admin_id TEXT NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      sent_at DATETIME
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'subject', type: 'TEXT', defaultSql: "''" },
      { name: 'message', type: 'TEXT', nullable: false },
      { name: 'type', type: 'TEXT', defaultSql: "'draft'" },
      { name: 'target_type', type: 'TEXT', defaultSql: "'all'" },
      { name: 'target_id', type: 'TEXT', defaultSql: "''" },
      { name: 'custom_emails', type: 'TEXT', defaultSql: "''" },
      { name: 'send_email', type: 'INTEGER', defaultSql: '1' },
      { name: 'send_notification', type: 'INTEGER', defaultSql: '1' },
      { name: 'send_push', type: 'INTEGER', defaultSql: '0' },
      { name: 'admin_id', type: 'TEXT', nullable: false },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'sent_at', type: 'DATETIME' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_broadcast_drafts_type ON BroadcastDrafts(type)',
      'CREATE INDEX IF NOT EXISTS idx_broadcast_drafts_admin ON BroadcastDrafts(admin_id)',
    ],
  },

  SiteSettings: {
    createSql: `CREATE TABLE IF NOT EXISTS SiteSettings (
      key TEXT PRIMARY KEY,
      value TEXT NOT NULL,
      description TEXT,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'key', type: 'TEXT' },
      { name: 'value', type: 'TEXT', nullable: false },
      { name: 'description', type: 'TEXT' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  PrepaidTimeBank: {
    createSql: `CREATE TABLE IF NOT EXISTS PrepaidTimeBank (
      user_id TEXT NOT NULL,
      session_id TEXT NOT NULL,
      prepaid_seconds INTEGER NOT NULL DEFAULT 0,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (user_id, session_id),
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (session_id) REFERENCES LiveSessions(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'session_id', type: 'TEXT', nullable: false },
      { name: 'prepaid_seconds', type: 'INTEGER', nullable: false, defaultSql: '0' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  IndividualBookings: {
    createSql: `CREATE TABLE IF NOT EXISTS IndividualBookings (
      id TEXT PRIMARY KEY,
      course_id TEXT NOT NULL,
      student_id TEXT NOT NULL,
      teacher_id TEXT NOT NULL,
      status TEXT CHECK(status IN ('scheduled', 'live', 'completed', 'cancelled')) NOT NULL DEFAULT 'scheduled',
      scheduled_at DATETIME NOT NULL,
      start_time DATETIME,
      end_time DATETIME,
      duration_minutes INTEGER DEFAULT 30,
      credits_charged INTEGER DEFAULT 0,
      credits_refunded INTEGER DEFAULT 0,
      live_session_id TEXT,
      google_event_id TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (course_id) REFERENCES Courses(id) ON DELETE CASCADE,
      FOREIGN KEY (student_id) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (teacher_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'course_id', type: 'TEXT', nullable: false },
      { name: 'student_id', type: 'TEXT', nullable: false },
      { name: 'teacher_id', type: 'TEXT', nullable: false },
      { name: 'status', type: 'TEXT', nullable: false, defaultSql: "'scheduled'" },
      { name: 'scheduled_at', type: 'DATETIME', nullable: false },
      { name: 'start_time', type: 'DATETIME' },
      { name: 'end_time', type: 'DATETIME' },
      { name: 'duration_minutes', type: 'INTEGER', defaultSql: '30' },
      { name: 'credits_charged', type: 'INTEGER', defaultSql: '0' },
      { name: 'credits_refunded', type: 'INTEGER', defaultSql: '0' },
      { name: 'live_session_id', type: 'TEXT' },
      { name: 'google_event_id', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  CreditWallets: {
    createSql: `CREATE TABLE IF NOT EXISTS CreditWallets (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL UNIQUE,
      balance INTEGER DEFAULT 0,
      lifetime_credits INTEGER DEFAULT 0,
      subscription_id TEXT,
      credits_period TEXT DEFAULT 'none',
      period_start DATETIME,
      period_end DATETIME,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'balance', type: 'INTEGER', defaultSql: '0' },
      { name: 'lifetime_credits', type: 'INTEGER', defaultSql: '0' },
      { name: 'subscription_id', type: 'TEXT' },
      { name: 'credits_period', type: 'TEXT', defaultSql: "'none'" },
      { name: 'period_start', type: 'DATETIME' },
      { name: 'period_end', type: 'DATETIME' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  CreditLedger: {
    createSql: `CREATE TABLE IF NOT EXISTS CreditLedger (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      change_amount INTEGER NOT NULL,
      balance_after INTEGER NOT NULL,
      reason TEXT NOT NULL,
      reference_type TEXT,
      reference_id TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'change_amount', type: 'INTEGER', nullable: false },
      { name: 'balance_after', type: 'INTEGER', nullable: false },
      { name: 'reason', type: 'TEXT', nullable: false },
      { name: 'reference_type', type: 'TEXT' },
      { name: 'reference_id', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_credit_ledger_user ON CreditLedger(user_id)',
      'CREATE INDEX IF NOT EXISTS idx_credit_ledger_reference ON CreditLedger(reference_type, reference_id)',
    ],
  },

  RateLimits: {
    createSql: `CREATE TABLE IF NOT EXISTS RateLimits (
      user_id TEXT NOT NULL,
      service TEXT NOT NULL DEFAULT 'ai',
      window_start DATETIME,
      window_used INTEGER DEFAULT 0,
      rate_limit INTEGER DEFAULT 0,
      PRIMARY KEY (user_id, service)
    )`,
    columns: [
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'service', type: 'TEXT', nullable: false, defaultSql: "'ai'" },
      { name: 'window_start', type: 'DATETIME' },
      { name: 'window_used', type: 'INTEGER', defaultSql: '0' },
      { name: 'rate_limit', type: 'INTEGER', defaultSql: '0' },
    ],
  },

  Transactions: {
    createSql: `CREATE TABLE IF NOT EXISTS Transactions (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      amount INTEGER,
      amount_paise INTEGER,
      amount_inr INTEGER,
      currency TEXT DEFAULT 'INR',
      type TEXT NOT NULL,
      status TEXT NOT NULL,
      razorpay_order_id TEXT,
      razorpay_payment_id TEXT,
      razorpay_signature TEXT,
      payment_source TEXT DEFAULT 'razorpay',
      related_id TEXT,
      credits_added INTEGER,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'amount', type: 'INTEGER' },
      { name: 'amount_paise', type: 'INTEGER' },
      { name: 'amount_inr', type: 'INTEGER' },
      { name: 'currency', type: 'TEXT', defaultSql: "'INR'" },
      { name: 'type', type: 'TEXT', nullable: false },
      { name: 'status', type: 'TEXT', nullable: false },
      { name: 'razorpay_order_id', type: 'TEXT' },
      { name: 'razorpay_payment_id', type: 'TEXT' },
      { name: 'razorpay_signature', type: 'TEXT' },
      { name: 'payment_source', type: 'TEXT', defaultSql: "'razorpay'" },
      { name: 'related_id', type: 'TEXT' },
      { name: 'credits_added', type: 'INTEGER' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_transactions_user ON Transactions(user_id)',
      'CREATE INDEX IF NOT EXISTS idx_transactions_order ON Transactions(razorpay_order_id)',
    ],
  },

  CreditPlans: {
    createSql: `CREATE TABLE IF NOT EXISTS CreditPlans (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      credits INTEGER NOT NULL,
      price_inr INTEGER NOT NULL,
      is_active INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'name', type: 'TEXT', nullable: false },
      { name: 'credits', type: 'INTEGER', nullable: false },
      { name: 'price_inr', type: 'INTEGER', nullable: false },
      { name: 'is_active', type: 'INTEGER', defaultSql: '1' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  Coupons: {
    createSql: `CREATE TABLE IF NOT EXISTS Coupons (
      id TEXT PRIMARY KEY,
      code TEXT UNIQUE NOT NULL,
      name TEXT,
      discount_type TEXT CHECK(discount_type IN ('percent','fixed')) NOT NULL DEFAULT 'percent',
      discount_value INTEGER NOT NULL DEFAULT 0,
      max_discount_paise INTEGER DEFAULT 0,
      min_order_paise INTEGER DEFAULT 0,
      applies_to_json TEXT DEFAULT '["all"]',
      target_ids_json TEXT DEFAULT '[]',
      allowed_emails_json TEXT DEFAULT '[]',
      excluded_emails_json TEXT DEFAULT '[]',
      usage_limit INTEGER,
      per_user_limit INTEGER DEFAULT 1,
      starts_at DATETIME,
      ends_at DATETIME,
      is_active INTEGER DEFAULT 1,
      created_by TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'code', type: 'TEXT', nullable: false },
      { name: 'name', type: 'TEXT' },
      { name: 'discount_type', type: 'TEXT', nullable: false, defaultSql: "'percent'" },
      { name: 'discount_value', type: 'INTEGER', nullable: false, defaultSql: '0' },
      { name: 'max_discount_paise', type: 'INTEGER', defaultSql: '0' },
      { name: 'min_order_paise', type: 'INTEGER', defaultSql: '0' },
      { name: 'applies_to_json', type: 'TEXT', defaultSql: '\'["all"]\'' },
      { name: 'target_ids_json', type: 'TEXT', defaultSql: "'[]'" },
      { name: 'allowed_emails_json', type: 'TEXT', defaultSql: "'[]'" },
      { name: 'excluded_emails_json', type: 'TEXT', defaultSql: "'[]'" },
      { name: 'usage_limit', type: 'INTEGER' },
      { name: 'per_user_limit', type: 'INTEGER', defaultSql: '1' },
      { name: 'starts_at', type: 'DATETIME' },
      { name: 'ends_at', type: 'DATETIME' },
      { name: 'is_active', type: 'INTEGER', defaultSql: '1' },
      { name: 'created_by', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  CouponRedemptions: {
    createSql: `CREATE TABLE IF NOT EXISTS CouponRedemptions (
      id TEXT PRIMARY KEY,
      coupon_id TEXT NOT NULL,
      user_id TEXT NOT NULL,
      item_type TEXT NOT NULL,
      item_id TEXT,
      transaction_id TEXT,
      discount_paise INTEGER DEFAULT 0,
      status TEXT DEFAULT 'created',
      redeemed_at DATETIME,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (coupon_id) REFERENCES Coupons(id) ON DELETE CASCADE,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'coupon_id', type: 'TEXT', nullable: false },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'item_type', type: 'TEXT', nullable: false },
      { name: 'item_id', type: 'TEXT' },
      { name: 'transaction_id', type: 'TEXT' },
      { name: 'discount_paise', type: 'INTEGER', defaultSql: '0' },
      { name: 'status', type: 'TEXT', defaultSql: "'created'" },
      { name: 'redeemed_at', type: 'DATETIME' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_coupon_user ON CouponRedemptions(coupon_id, user_id)',
    ],
  },

  BillingAddresses: {
    createSql: `CREATE TABLE IF NOT EXISTS BillingAddresses (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      transaction_id TEXT,
      full_name TEXT,
      email TEXT,
      phone TEXT,
      line1 TEXT,
      line2 TEXT,
      city TEXT,
      state TEXT,
      pincode TEXT,
      country TEXT DEFAULT 'India',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'transaction_id', type: 'TEXT' },
      { name: 'full_name', type: 'TEXT' },
      { name: 'email', type: 'TEXT' },
      { name: 'phone', type: 'TEXT' },
      { name: 'line1', type: 'TEXT' },
      { name: 'line2', type: 'TEXT' },
      { name: 'city', type: 'TEXT' },
      { name: 'state', type: 'TEXT' },
      { name: 'pincode', type: 'TEXT' },
      { name: 'country', type: 'TEXT', defaultSql: "'India'" },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_billing_addresses_user ON BillingAddresses(user_id)',
    ],
  },

  Books: {
    createSql: `CREATE TABLE IF NOT EXISTS Books (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      description TEXT,
      price_inr INTEGER DEFAULT 0,
      price_usd INTEGER DEFAULT 0,
      thumbnail_url TEXT,
      is_standalone INTEGER DEFAULT 0,
      self_study_enabled INTEGER DEFAULT 0,
      self_study_credit_cost INTEGER DEFAULT 0,
      title_hi TEXT,
      description_hi TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'title', type: 'TEXT', nullable: false },
      { name: 'description', type: 'TEXT' },
      { name: 'price_inr', type: 'INTEGER', defaultSql: '0' },
      { name: 'price_usd', type: 'INTEGER', defaultSql: '0' },
      { name: 'thumbnail_url', type: 'TEXT' },
      { name: 'is_standalone', type: 'INTEGER', defaultSql: '0' },
      { name: 'self_study_enabled', type: 'INTEGER', defaultSql: '0' },
      { name: 'self_study_credit_cost', type: 'INTEGER', defaultSql: '0' },
      { name: 'title_hi', type: 'TEXT' },
      { name: 'description_hi', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  CourseBooks: {
    createSql: `CREATE TABLE IF NOT EXISTS CourseBooks (
      course_id TEXT NOT NULL,
      book_id TEXT NOT NULL,
      order_index INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY (course_id, book_id),
      FOREIGN KEY (course_id) REFERENCES Courses(id) ON DELETE CASCADE,
      FOREIGN KEY (book_id) REFERENCES Books(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'course_id', type: 'TEXT', nullable: false },
      { name: 'book_id', type: 'TEXT', nullable: false },
      { name: 'order_index', type: 'INTEGER', nullable: false, defaultSql: '0' },
    ],
  },

  Badges: {
    createSql: `CREATE TABLE IF NOT EXISTS Badges (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      icon TEXT DEFAULT 'Trophy',
      xp_reward INTEGER DEFAULT 0,
      criteria_type TEXT NOT NULL,
      criteria_value INTEGER NOT NULL,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'name', type: 'TEXT', nullable: false },
      { name: 'description', type: 'TEXT' },
      { name: 'icon', type: 'TEXT', defaultSql: "'Trophy'" },
      { name: 'xp_reward', type: 'INTEGER', defaultSql: '0' },
      { name: 'criteria_type', type: 'TEXT', nullable: false },
      { name: 'criteria_value', type: 'INTEGER', nullable: false },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  LeaveRequests: {
    createSql: `CREATE TABLE IF NOT EXISTS LeaveRequests (
      id TEXT PRIMARY KEY,
      student_id TEXT NOT NULL,
      course_id TEXT,
      batch_id TEXT,
      start_date TEXT NOT NULL,
      end_date TEXT NOT NULL,
      reason TEXT NOT NULL,
      type TEXT CHECK(type IN ('sick', 'personal', 'other')) DEFAULT 'other',
      status TEXT CHECK(status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
      reviewed_by TEXT,
      reviewed_at TEXT,
      admin_notes TEXT,
      google_event_id TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (student_id) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (course_id) REFERENCES Courses(id) ON DELETE SET NULL,
      FOREIGN KEY (batch_id) REFERENCES Batches(id) ON DELETE SET NULL,
      FOREIGN KEY (reviewed_by) REFERENCES Users(id) ON DELETE SET NULL
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'student_id', type: 'TEXT', nullable: false },
      { name: 'course_id', type: 'TEXT' },
      { name: 'batch_id', type: 'TEXT' },
      { name: 'start_date', type: 'TEXT', nullable: false },
      { name: 'end_date', type: 'TEXT', nullable: false },
      { name: 'reason', type: 'TEXT', nullable: false },
      { name: 'type', type: 'TEXT', defaultSql: "'other'" },
      { name: 'status', type: 'TEXT', defaultSql: "'pending'" },
      { name: 'reviewed_by', type: 'TEXT' },
      { name: 'reviewed_at', type: 'TEXT' },
      { name: 'admin_notes', type: 'TEXT' },
      { name: 'google_event_id', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_leave_student ON LeaveRequests(student_id)',
      'CREATE INDEX IF NOT EXISTS idx_leave_status ON LeaveRequests(status)',
      'CREATE INDEX IF NOT EXISTS idx_leave_course ON LeaveRequests(course_id)',
      'CREATE INDEX IF NOT EXISTS idx_leave_batch ON LeaveRequests(batch_id)',
    ],
  },

  UserBadges: {
    createSql: `CREATE TABLE IF NOT EXISTS UserBadges (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      badge_id TEXT NOT NULL,
      earned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (badge_id) REFERENCES Badges(id) ON DELETE CASCADE,
      UNIQUE(user_id, badge_id)
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'badge_id', type: 'TEXT', nullable: false },
      { name: 'earned_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  CourseMerchantListings: {
    createSql: `CREATE TABLE IF NOT EXISTS CourseMerchantListings (
      id TEXT PRIMARY KEY,
      course_id TEXT UNIQUE NOT NULL,
      sync_enabled INTEGER DEFAULT 1,
      offer_id TEXT,
      content_language TEXT,
      feed_label TEXT,
      target_country TEXT,
      currency TEXT,
      availability TEXT,
      condition TEXT,
      brand TEXT,
      google_product_category TEXT,
      image_url TEXT,
      landing_url TEXT,
      product_resource_name TEXT,
      data_source_name TEXT,
      sync_status TEXT DEFAULT 'not_synced',
      sync_error TEXT,
      last_synced_at DATETIME,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (course_id) REFERENCES Courses(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'course_id', type: 'TEXT', nullable: false },
      { name: 'sync_enabled', type: 'INTEGER', defaultSql: '1' },
      { name: 'offer_id', type: 'TEXT' },
      { name: 'content_language', type: 'TEXT' },
      { name: 'feed_label', type: 'TEXT' },
      { name: 'target_country', type: 'TEXT' },
      { name: 'currency', type: 'TEXT' },
      { name: 'availability', type: 'TEXT' },
      { name: 'condition', type: 'TEXT' },
      { name: 'brand', type: 'TEXT' },
      { name: 'google_product_category', type: 'TEXT' },
      { name: 'image_url', type: 'TEXT' },
      { name: 'landing_url', type: 'TEXT' },
      { name: 'product_resource_name', type: 'TEXT' },
      { name: 'data_source_name', type: 'TEXT' },
      { name: 'sync_status', type: 'TEXT', defaultSql: "'not_synced'" },
      { name: 'sync_error', type: 'TEXT' },
      { name: 'last_synced_at', type: 'DATETIME' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_merchant_course ON CourseMerchantListings(course_id)',
    ],
  },

  CreditPacks: {
    createSql: `CREATE TABLE IF NOT EXISTS CreditPacks (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      amount_inr INTEGER NOT NULL,
      credits INTEGER NOT NULL,
      credit_type TEXT,
      is_active INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'name', type: 'TEXT', nullable: false },
      { name: 'description', type: 'TEXT' },
      { name: 'amount_inr', type: 'INTEGER', nullable: false },
      { name: 'credits', type: 'INTEGER', nullable: false },
      { name: 'credit_type', type: 'TEXT' },
      { name: 'is_active', type: 'INTEGER', defaultSql: '1' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_creditpacks_active ON CreditPacks(is_active)',
    ],
  },

  Subscriptions: {
    createSql: `CREATE TABLE IF NOT EXISTS Subscriptions (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      plan_id TEXT NOT NULL,
      razorpay_subscription_id TEXT,
      razorpay_payment_link TEXT,
      status TEXT DEFAULT 'created',
      live_class_credits INTEGER DEFAULT 0,
      is_lifetime INTEGER DEFAULT 0,
      current_period_start TEXT,
      current_period_end TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (plan_id) REFERENCES SubscriptionPlans(id) ON DELETE CASCADE
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'plan_id', type: 'TEXT', nullable: false },
      { name: 'razorpay_subscription_id', type: 'TEXT' },
      { name: 'razorpay_payment_link', type: 'TEXT' },
      { name: 'status', type: 'TEXT', defaultSql: "'created'" },
      { name: 'live_class_credits', type: 'INTEGER', defaultSql: '0' },
      { name: 'is_lifetime', type: 'INTEGER', defaultSql: '0' },
      { name: 'current_period_start', type: 'TEXT' },
      { name: 'current_period_end', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON Subscriptions(user_id)',
      'CREATE INDEX IF NOT EXISTS idx_subscriptions_razorpay ON Subscriptions(razorpay_subscription_id)',
    ],
  },

  SubscriptionPlans: {
    createSql: `CREATE TABLE IF NOT EXISTS SubscriptionPlans (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      interval TEXT NOT NULL,
      interval_count INTEGER DEFAULT 1,
      amount_inr INTEGER NOT NULL,
      razorpay_plan_id TEXT,
      course_access_type TEXT,
      max_course_selection INTEGER DEFAULT 0,
      batch_access_type TEXT,
      max_batch_selection INTEGER DEFAULT 0,
      book_access_type TEXT,
      max_book_selection INTEGER DEFAULT 0,
      ai_credits INTEGER DEFAULT 0,
      ai_credits_period TEXT,
      ai_rate_limit_per_hour INTEGER DEFAULT 0,
      live_session_access INTEGER DEFAULT 0,
      live_class_credits INTEGER DEFAULT 0,
      is_lifetime INTEGER DEFAULT 0,
      is_active INTEGER DEFAULT 1,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'name', type: 'TEXT', nullable: false },
      { name: 'interval', type: 'TEXT', nullable: false },
      { name: 'interval_count', type: 'INTEGER', defaultSql: '1' },
      { name: 'amount_inr', type: 'INTEGER', nullable: false },
      { name: 'razorpay_plan_id', type: 'TEXT' },
      { name: 'course_access_type', type: 'TEXT' },
      { name: 'max_course_selection', type: 'INTEGER', defaultSql: '0' },
      { name: 'batch_access_type', type: 'TEXT' },
      { name: 'max_batch_selection', type: 'INTEGER', defaultSql: '0' },
      { name: 'book_access_type', type: 'TEXT' },
      { name: 'max_book_selection', type: 'INTEGER', defaultSql: '0' },
      { name: 'ai_credits', type: 'INTEGER', defaultSql: '0' },
      { name: 'ai_credits_period', type: 'TEXT' },
      { name: 'ai_rate_limit_per_hour', type: 'INTEGER', defaultSql: '0' },
      { name: 'live_session_access', type: 'INTEGER', defaultSql: '0' },
      { name: 'live_class_credits', type: 'INTEGER', defaultSql: '0' },
      { name: 'is_lifetime', type: 'INTEGER', defaultSql: '0' },
      { name: 'is_active', type: 'INTEGER', defaultSql: '1' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_subscription_plans_active ON SubscriptionPlans(is_active)',
    ],
  },

  ReleaseCampaigns: {
    createSql: `CREATE TABLE IF NOT EXISTS ReleaseCampaigns (
      id TEXT PRIMARY KEY,
      source_branch TEXT,
      target_branch TEXT,
      merge_sha TEXT,
      status TEXT,
      change_summary TEXT,
      email_subject TEXT,
      email_body TEXT,
      social_post TEXT,
      article_status TEXT DEFAULT 'coming_soon',
      social_platforms TEXT,
      scheduled_at DATETIME,
      email_sent_count INTEGER DEFAULT 0,
      social_result TEXT,
      admin_id TEXT,
      completed_at DATETIME,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (admin_id) REFERENCES Users(id) ON DELETE SET NULL
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'source_branch', type: 'TEXT' },
      { name: 'target_branch', type: 'TEXT' },
      { name: 'merge_sha', type: 'TEXT' },
      { name: 'status', type: 'TEXT' },
      { name: 'change_summary', type: 'TEXT' },
      { name: 'email_subject', type: 'TEXT' },
      { name: 'email_body', type: 'TEXT' },
      { name: 'social_post', type: 'TEXT' },
      { name: 'article_status', type: 'TEXT', defaultSql: "'coming_soon'" },
      { name: 'social_platforms', type: 'TEXT' },
      { name: 'scheduled_at', type: 'DATETIME' },
      { name: 'email_sent_count', type: 'INTEGER', defaultSql: '0' },
      { name: 'social_result', type: 'TEXT' },
      { name: 'admin_id', type: 'TEXT' },
      { name: 'completed_at', type: 'DATETIME' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
  },

  UserSubscriptionSelections: {
    createSql: `CREATE TABLE IF NOT EXISTS UserSubscriptionSelections (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      subscription_id TEXT NOT NULL,
      item_type TEXT NOT NULL,
      item_id TEXT NOT NULL,
      FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (subscription_id) REFERENCES Subscriptions(id) ON DELETE CASCADE,
      UNIQUE(subscription_id, item_type, item_id)
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'user_id', type: 'TEXT', nullable: false },
      { name: 'subscription_id', type: 'TEXT', nullable: false },
      { name: 'item_type', type: 'TEXT', nullable: false },
      { name: 'item_id', type: 'TEXT', nullable: false },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_uss_subscription ON UserSubscriptionSelections(subscription_id)',
      'CREATE INDEX IF NOT EXISTS idx_uss_user ON UserSubscriptionSelections(user_id)',
    ],
  },

  PlanContentPool: {
    createSql: `CREATE TABLE IF NOT EXISTS PlanContentPool (
      id TEXT PRIMARY KEY,
      plan_id TEXT NOT NULL,
      item_type TEXT NOT NULL,
      item_id TEXT NOT NULL,
      access_mode TEXT,
      bonus_ai_credits INTEGER DEFAULT 0,
      FOREIGN KEY (plan_id) REFERENCES SubscriptionPlans(id) ON DELETE CASCADE,
      UNIQUE(plan_id, item_type, item_id)
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'plan_id', type: 'TEXT', nullable: false },
      { name: 'item_type', type: 'TEXT', nullable: false },
      { name: 'item_id', type: 'TEXT', nullable: false },
      { name: 'access_mode', type: 'TEXT' },
      { name: 'bonus_ai_credits', type: 'INTEGER', defaultSql: '0' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_pcp_plan ON PlanContentPool(plan_id)',
      'CREATE INDEX IF NOT EXISTS idx_pcp_item ON PlanContentPool(plan_id, item_type)',
    ],
  },

  AnonymousUsers: {
    createSql: `CREATE TABLE IF NOT EXISTS AnonymousUsers (
      id TEXT PRIMARY KEY,
      device_id TEXT UNIQUE NOT NULL,
      first_seen_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      last_active_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      ip_address TEXT,
      user_agent TEXT,
      live_class_reminders_count INTEGER DEFAULT 0,
      live_class_reminders_reset_at DATETIME,
      broadcast_count INTEGER DEFAULT 0,
      broadcast_reset_at DATETIME,
      converted_to_user_id TEXT,
      converted_at DATETIME
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'device_id', type: 'TEXT', nullable: false },
      { name: 'first_seen_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'last_active_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'ip_address', type: 'TEXT' },
      { name: 'user_agent', type: 'TEXT' },
      { name: 'live_class_reminders_count', type: 'INTEGER', defaultSql: '0' },
      { name: 'live_class_reminders_reset_at', type: 'DATETIME' },
      { name: 'broadcast_count', type: 'INTEGER', defaultSql: '0' },
      { name: 'broadcast_reset_at', type: 'DATETIME' },
      { name: 'converted_to_user_id', type: 'TEXT' },
      { name: 'converted_at', type: 'DATETIME' },
    ],
    indexes: [
      'CREATE UNIQUE INDEX IF NOT EXISTS idx_anon_device ON AnonymousUsers(device_id)',
      'CREATE INDEX IF NOT EXISTS idx_anon_last_active ON AnonymousUsers(last_active_at)',
      'CREATE INDEX IF NOT EXISTS idx_anon_converted ON AnonymousUsers(converted_to_user_id)',
    ],
  },

  BroadcastLog: {
    createSql: `CREATE TABLE IF NOT EXISTS BroadcastLog (
      id TEXT PRIMARY KEY,
      sent_by TEXT,
      audience TEXT NOT NULL,
      title TEXT NOT NULL,
      body TEXT NOT NULL,
      data_json TEXT,
      sent_count INTEGER DEFAULT 0,
      failed_count INTEGER DEFAULT 0,
      skip_count INTEGER DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (sent_by) REFERENCES Users(id) ON DELETE SET NULL
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'sent_by', type: 'TEXT' },
      { name: 'audience', type: 'TEXT', nullable: false },
      { name: 'title', type: 'TEXT', nullable: false },
      { name: 'body', type: 'TEXT', nullable: false },
      { name: 'data_json', type: 'TEXT' },
      { name: 'sent_count', type: 'INTEGER', defaultSql: '0' },
      { name: 'failed_count', type: 'INTEGER', defaultSql: '0' },
      { name: 'skip_count', type: 'INTEGER', defaultSql: '0' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_broadcast_sent_by ON BroadcastLog(sent_by)',
      'CREATE INDEX IF NOT EXISTS idx_broadcast_created ON BroadcastLog(created_at)',
    ],
  },
  ScheduledNotifications: {
    createSql: `CREATE TABLE IF NOT EXISTS ScheduledNotifications (
      id TEXT PRIMARY KEY,
      created_by TEXT NOT NULL,
      title TEXT NOT NULL,
      title_hi TEXT,
      body TEXT NOT NULL,
      body_hi TEXT,
      audience TEXT NOT NULL,
      target_user_ids TEXT,
      data_json TEXT,
      schedule_type TEXT NOT NULL,
      scheduled_at DATETIME,
      time_of_day TEXT,
      days_of_week TEXT,
      days_of_month TEXT,
      timezone TEXT DEFAULT 'Asia/Kolkata',
      status TEXT DEFAULT 'pending',
      last_run_at DATETIME,
      next_run_at DATETIME,
      run_count INTEGER DEFAULT 0,
      max_runs INTEGER DEFAULT 100,
      expires_at DATETIME,
      result_log_id TEXT,
      last_error TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (created_by) REFERENCES Users(id) ON DELETE CASCADE,
      FOREIGN KEY (result_log_id) REFERENCES BroadcastLog(id) ON DELETE SET NULL
    )`,
    columns: [
      { name: 'id', type: 'TEXT' },
      { name: 'created_by', type: 'TEXT', nullable: false },
      { name: 'title', type: 'TEXT', nullable: false },
      { name: 'title_hi', type: 'TEXT' },
      { name: 'body', type: 'TEXT', nullable: false },
      { name: 'body_hi', type: 'TEXT' },
      { name: 'audience', type: 'TEXT', nullable: false },
      { name: 'target_user_ids', type: 'TEXT' },
      { name: 'data_json', type: 'TEXT' },
      { name: 'schedule_type', type: 'TEXT', nullable: false },
      { name: 'scheduled_at', type: 'DATETIME' },
      { name: 'time_of_day', type: 'TEXT' },
      { name: 'days_of_week', type: 'TEXT' },
      { name: 'days_of_month', type: 'TEXT' },
      { name: 'timezone', type: 'TEXT', defaultSql: "'Asia/Kolkata'" },
      { name: 'status', type: 'TEXT', defaultSql: "'pending'" },
      { name: 'last_run_at', type: 'DATETIME' },
      { name: 'next_run_at', type: 'DATETIME' },
      { name: 'run_count', type: 'INTEGER', defaultSql: '0' },
      { name: 'max_runs', type: 'INTEGER', defaultSql: '100' },
      { name: 'expires_at', type: 'DATETIME' },
      { name: 'result_log_id', type: 'TEXT' },
      { name: 'last_error', type: 'TEXT' },
      { name: 'created_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
      { name: 'updated_at', type: 'DATETIME', defaultSql: 'CURRENT_TIMESTAMP' },
    ],
    indexes: [
      'CREATE INDEX IF NOT EXISTS idx_sched_status ON ScheduledNotifications(status)',
      'CREATE INDEX IF NOT EXISTS idx_sched_next_run ON ScheduledNotifications(next_run_at)',
      'CREATE INDEX IF NOT EXISTS idx_sched_created_by ON ScheduledNotifications(created_by)',
      'CREATE INDEX IF NOT EXISTS idx_sched_created_at ON ScheduledNotifications(created_at)',
    ],
  },
};
