packages: []
allowBuilds:
  '@firebase/util': set this to true or false
  '@google/genai': set this to true or false
  '@tailwindcss/oxide': set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - '@google/genai'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - protobufjs
  - re2
  - sharp
  - unrs-resolver
overrides:
  closure-net: npm:closure-net@0.0.1-security

