/// <reference path="../worker-configuration.d.ts" />
import { parseJsonRequestBody } from "./request-utils";

// Shared, dependency-free helpers extracted from src/index.ts during the
// index.ts split. Function names and behavior are unchanged so callers in
// index.ts (and future domain modules) can import them directly. Do not add
// helpers here that depend on domain code (auth, error sessions, Jules,
// site settings, etc.); those belong in their own modules to avoid circular
// imports.

// Extends __BaseEnv_Env from worker-configuration.d.ts (auto-generated by `wrangler types`).
// AI/AI_SEARCH are widened to `any` because the code uses loose access patterns
// (e.g., visionResponse.description) that don't match the strict auto-generated response types.
export interface Env extends __BaseEnv_Env {
  AI: any;
  AI_SEARCH: any;
}

export function escapeLikePattern(str: string): string {
  return str.replace(/[\\%_]/g, "\\$&");
}

export function getISTTime(date: Date | number | string = new Date()): string {
  return new Date(date).toLocaleString("en-IN", {
    timeZone: "Asia/Kolkata",
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });
}

/**
 * Returns current time in UTC ISO string for consistent DB storage.
 */
export function getUTCNow(): string {
  return new Date().toISOString();
}

export async function computeChecksum(data: string): Promise<string> {
  const encoder = new TextEncoder();
  const digest = await crypto.subtle.digest("SHA-256", encoder.encode(data));
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Extracts IP from request headers.
 */
export function getClientIP(request: Request): string {
  return (
    request.headers.get("cf-connecting-ip") ||
    request.headers.get("x-real-ip") ||
    "Unknown"
  );
}

export async function parseRequestBody(request: Request): Promise<any> {
  return parseJsonRequestBody(request);
}

export function uint8ArrayToBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary)
    .replace(/=/g, "")
    .replace(/\+/g, "-")
    .replace(/\//g, "_");
}

export function safeParseJsonValue<T = any>(value: string | null | undefined, fallback: T): T {
  if (!value) return fallback;
  try {
    return JSON.parse(value) as T;
  } catch (_) {
    return fallback;
  }
}

export function truncateText(value: string | null | undefined, max = 24000): string {
  if (!value) return "";
  return value.length > max ? `${value.slice(0, max)}\n...[truncated ${value.length - max} chars]` : value;
}

export function truncateLongStrings(obj: any, maxStrLen = 20000, maxArrayLen = 200): any {
  if (typeof obj === "string") {
    return obj.length > maxStrLen ? `${obj.slice(0, maxStrLen)}\n...[truncated ${obj.length - maxStrLen} chars]` : obj;
  }
  if (Array.isArray(obj)) {
    const newArr = obj.slice(0, maxArrayLen).map((item) => truncateLongStrings(item, maxStrLen, maxArrayLen));
    if (obj.length > maxArrayLen) {
      newArr.push(`...[truncated ${obj.length - maxArrayLen} items]`);
    }
    return newArr;
  }
  if (obj !== null && typeof obj === "object") {
    const newObj: any = {};
    for (const key in obj) {
      newObj[key] = truncateLongStrings(obj[key], maxStrLen, maxArrayLen);
    }
    return newObj;
  }
  return obj;
}

export async function sha256Hex(input: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export function inrToPaise(inr: number): number {
  return Math.round(Math.max(0, Number(inr) || 0) * 100);
}

export function paiseToInr(paise: number): number {
  // #675: round (not floor) so fractional rupees aren't lost when converting paise -> rupees.
  return Math.round(Math.max(0, Number(paise) || 0)) / 100;
}

export function escapeHtml(value: any): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function stripHtml(value: any): string {
  return String(value ?? "")
    .replace(/<[^>]*>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function normalizeBoolean(value: any): boolean {
  return value === true || value === 1 || value === "1" || value === "true" || value === "on";
}

export function timingSafeEqual(a: string, b: string): boolean {
  const aBytes = new TextEncoder().encode(a);
  const bBytes = new TextEncoder().encode(b);
  const maxLen = Math.max(aBytes.length, bBytes.length);
  // Seed diff with length XOR so different lengths inevitably produce non-zero
  let diff = aBytes.length ^ bBytes.length;
  for (let i = 0; i < maxLen; i++) {
    diff |= (aBytes[i] ?? 0) ^ (bBytes[i] ?? 0);
  }
  return diff === 0;
}

/**
 * Convert a hex string to Uint8Array for use with Web Crypto API verify().
 */
export function hexToBytes(hex: string): Uint8Array<ArrayBuffer> {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes as Uint8Array<ArrayBuffer>;
}

export function getCookie(request: Request, name: string): string | null {
  const cookieHeader = request.headers.get("Cookie");
  if (!cookieHeader) return null;
  const cookies = cookieHeader.split(';').map(c => c.trim());
  for (const cookie of cookies) {
    if (cookie.startsWith(`${name}=`)) {
      return cookie.substring(name.length + 1);
    }
  }
  return null;
}

export function base64UrlDecodeToUint8Array(str: string): Uint8Array<ArrayBuffer> {
  const base64 = str.replace(/-/g, "+").replace(/_/g, "/");
  const pad = base64.length % 4;
  const padded = pad ? base64 + "=".repeat(4 - pad) : base64;
  const decoded = atob(padded);
  const bytes = new Uint8Array(decoded.length);
  for (let i = 0; i < decoded.length; i++) {
    bytes[i] = decoded.charCodeAt(i);
  }
  return bytes as Uint8Array<ArrayBuffer>;
}

export function base64UrlDecodeToString(str: string): string {
  return new TextDecoder().decode(base64UrlDecodeToUint8Array(str));
}

export function chunkArray<T>(arr: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let i = 0; i < arr.length; i += size) chunks.push(arr.slice(i, i + size));
  return chunks;
}

export function jsonResponse(body: any, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });
}

export function base64UrlEncodeBytes(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
}

export function base64UrlEncodeJson(value: any): string {
  return btoa(JSON.stringify(value)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
}

export function generateCustomId(prefix: string): string {
  const randomPart = crypto.randomUUID().substring(0, 12).toUpperCase();
  const timestampPart = Date.now().toString(36).toUpperCase().slice(-6);
  return `${prefix}-${randomPart}${timestampPart}`;
}

export function sanitizeJson(text: string): string {
  if (!text) return "{}";

  // Replace smart/curly quotes with standard quotes
  let sanitized = text.replace(/[\u201C\u201D\u201E\u201F\u2033\u2036]/g, '"');

  // Remove markdown blocks
  sanitized = sanitized
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .trim();

  // Extract JSON string
  const firstBrace = sanitized.indexOf("{");
  const lastBrace = sanitized.lastIndexOf("}");
  if (firstBrace !== -1 && lastBrace !== -1) {
    sanitized = sanitized.substring(firstBrace, lastBrace + 1);
  } else {
    // If AI hallucinates plain text instead of JSON, wrap it safely
    // so JSON.parse doesn't crash downstream.
    return JSON.stringify({ reply: text.trim() });
  }

  // Safest for AI output that is just simple JSON is to remove newlines completely.
  sanitized = sanitized
    .replace(/\n/g, " ")
    .replace(/\r/g, " ")
    .replace(/\t/g, " ");
  sanitized = sanitized.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F]/g, "");

  return sanitized;
}
